spring.application.name=placementcoach

spring.security.user.name=admin
spring.security.user.password=admin

spring.datasource.url=jdbc:postgresql://localhost:5432/placementcoach
spring.datasource.username=postgres
spring.datasource.password=postgres123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true